Update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,10 +36,31 @@ jobs:
               key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
               restore-keys: ${{ runner.os }}-terraform-
 
-          - name: Terraform validate modules
+          - name: Terraform validate modules and collect failures
+            id: validate
             run: |
+              failed_modules=()
               for dir in $(find ./modules -type d -mindepth 1 -maxdepth 1); do
+                # hack: dont need provider alias during ci
+                pushd $dir
+                    gsed -i '/databricks.mws/d' *.tf
+                popd
                 echo "Processing module $dir"
-                terraform -chdir=$dir init -backend=false
-                terraform -chdir=$dir validate
+                terraform -chdir=$dir init -lock=false -backend=false -input=false
+                if ! terraform -chdir=$dir validate; then
+                  failed_modules+=($dir)
+                fi
               done
+              echo "failed_modules=${failed_modules[@]}" >> $GITHUB_ENV
+
+          - name: Output failed modules
+            run: |
+              if [ -n "${{ env.failed_modules }}" ]; then
+                echo "The following modules failed validation:"
+                for module in ${{ env.failed_modules }}; do
+                  echo $module
+                done
+                exit 1
+              else
+                echo "All modules passed validation."
+              fi
